-- `Test/FinDomain/Meta.lean` -- subdirectory aggregator
--
-- Imports 4 test modules from `Test/FinDomain/Meta/`.
--
-- Generated by `Scripts/gen_test_aggregators.py`; do not edit by hand.
-- Every module listed below is a test that currently passes.

import Test.FinDomain.Meta.KnightsTourArbitrary
import Test.FinDomain.Meta.LightsOutArbitrary
import Test.FinDomain.Meta.Sudoku9Inkala
import Test.FinDomain.Meta.ThreeColoring
