-- `Test/DiscMath.lean` -- subdirectory aggregator
--
-- Imports 1 test module from `Test/DiscMath/`.
--
-- Generated by `Scripts/gen_test_aggregators.py`; do not edit by hand.
-- Every module listed below is a test that currently passes.

import Test.DiscMath.Recurent
