-- `Test/FinDomain.lean` -- subdirectory aggregator
--
-- Imports 32 test modules from `Test/FinDomain/`.
--
-- Generated by `Scripts/gen_test_aggregators.py`; do not edit by hand.
-- Every module listed below is a test that currently passes.

import Test.FinDomain.BalancedBST
import Test.FinDomain.Cryptarithm
import Test.FinDomain.DistanceCode
import Test.FinDomain.EightQueensSat
import Test.FinDomain.EightQueensUnsat
import Test.FinDomain.EraseReplacePreimage
import Test.FinDomain.ExactCover
import Test.FinDomain.FilterPartitionCount
import Test.FinDomain.FinGroup
import Test.FinDomain.GraphIso
import Test.FinDomain.IdxFindFromValues
import Test.FinDomain.KnightsTour
import Test.FinDomain.MinSubsetExceed
import Test.FinDomain.NimStrategy
import Test.FinDomain.Nonogram
import Test.FinDomain.ReverseMapChain
import Test.FinDomain.SafetyInvariant
import Test.FinDomain.ShortestPath
import Test.FinDomain.SortPerm
import Test.FinDomain.SortingNetwork
import Test.FinDomain.SplitRejoin
import Test.FinDomain.StarBattle10x10
import Test.FinDomain.SubsetSum
import Test.FinDomain.Sudoku9
import Test.FinDomain.Sudoku9Inkala
import Test.FinDomain.Sudoku9Partial
import Test.FinDomain.TakeDropExact
import Test.FinDomain.ThreeColoringSat
import Test.FinDomain.ThreeColoringUnsat
import Test.FinDomain.TogglePlan
import Test.FinDomain.TopoSort
import Test.FinDomain.TwoGuards

-- nested subdirectories
import Test.FinDomain.Meta
