-- `Test/Inductive.lean` -- subdirectory aggregator
--
-- Imports 1 test module from `Test/Inductive/`.
--
-- Generated by `Scripts/gen_test_aggregators.py`; do not edit by hand.
-- Every module listed below is a test that currently passes.

import Test.Inductive.NatDefs
