-- `Test/Interval.lean` -- subdirectory aggregator
--
-- Imports 6 test modules from `Test/Interval/`.
--
-- Generated by `Scripts/gen_test_aggregators.py`; do not edit by hand.
-- Every module listed below is a test that currently passes.

import Test.Interval.Approx
import Test.Interval.Closed
import Test.Interval.Euler
import Test.Interval.Exp
import Test.Interval.Floor
import Test.Interval.Gamma
