-- `Test/IntervalArith.lean` -- subdirectory aggregator
--
-- Imports 19 test modules from `Test/IntervalArith/`.
--
-- Generated by `Scripts/gen_test_aggregators.py`; do not edit by hand.
-- Every module listed below is a test that currently passes.

import Test.IntervalArith.ApproxRoots
import Test.IntervalArith.Basic
import Test.IntervalArith.Compositions
import Test.IntervalArith.Differentiation
import Test.IntervalArith.Discrete
import Test.IntervalArith.Extrema
import Test.IntervalArith.ImproperIntegrals
import Test.IntervalArith.InfiniteSums
import Test.IntervalArith.Integrals
import Test.IntervalArith.Linear
import Test.IntervalArith.LinearAlgebra
import Test.IntervalArith.Meta
import Test.IntervalArith.Ranges
import Test.IntervalArith.Roots
import Test.IntervalArith.ScratchSeries
import Test.IntervalArith.Special
import Test.IntervalArith.Sums
import Test.IntervalArith.Taylor
import Test.IntervalArith.Theorems
