-- `Test/ProgSynth.lean` -- subdirectory aggregator
--
-- Imports 14 test modules from `Test/ProgSynth/`.
--
-- Generated by `Scripts/gen_test_aggregators.py`; do not edit by hand.
-- Every module listed below is a test that currently passes.

import Test.ProgSynth.BST
import Test.ProgSynth.Bits
import Test.ProgSynth.Compress
import Test.ProgSynth.Dedup
import Test.ProgSynth.ExtractMin
import Test.ProgSynth.Intersection
import Test.ProgSynth.NNF
import Test.ProgSynth.Replicate
import Test.ProgSynth.ReplicateEach
import Test.ProgSynth.SortedUnion
import Test.ProgSynth.Split
import Test.ProgSynth.Suffixes
import Test.ProgSynth.TakeLast
import Test.ProgSynth.Union
