-- `Test.lean` -- root aggregator
--
-- Imports every currently-passing test in `Test/`.  Each
-- subdirectory is funnelled through its own aggregator, so this
-- file stays readable and a subtree can be built on its own.
-- The vendored `Test/Grind/` suite is deliberately absent.
--
-- Generated by `Scripts/gen_test_aggregators.py`; do not edit by hand.
-- Every module listed below is a test that currently passes.

-- subdirectory aggregators
import Test.DiscMath
import Test.FinDomain
import Test.FinSearch.Suite
import Test.Inductive
import Test.Interval
import Test.IntervalArith
import Test.Poly
import Test.ProgSynth
import Test.Sat.Suite

-- root-level tests
import Test.Arith
import Test.ArithTactics
import Test.Arrays
import Test.BV
import Test.BVBlast
import Test.BranchBound
import Test.Cdcl
import Test.CdclFuzz
import Test.Corpus
import Test.Datatypes
import Test.Encode
import Test.Euf
import Test.Farkas
import Test.FarkasSound
import Test.FinFuzz
import Test.FinSearch
import Test.FinSearchAlt
import Test.Nlin
import Test.Quant
import Test.Readme
import Test.Ring
import Test.Robust
import Test.Sat
import Test.Simplex
import Test.Spec
import Test.StarBattle
import Test.Tactics
import Test.Tseitin
import Test.Witness
