-- `Test/Sat/Suite.lean` -- subdirectory aggregator
--
-- Imports 4 test modules from `Test/Sat/`.
--
-- Generated by `Scripts/gen_test_aggregators.py`; do not edit by hand.
-- Every module listed below is a test that currently passes.

import Test.Sat.CompileTest
import Test.Sat.FinValDifferTest
import Test.Sat.GatesTest
import Test.Sat.SolveLoop
