#!/usr/bin/env python3
"""Generate the aggregator modules and rewrite the root Test.lean.

Layout produced:

  Test.lean                    imports every aggregator + every root-level test
  Test/FinDomain.lean          imports the 32 modules in Test/FinDomain/, and
                               Test.FinDomain.Meta for the nested subdirectory
  Test/FinDomain/Meta.lean     imports its 4 modules
  Test/IntervalArith.lean      ... and so on for each subdirectory
  Test/Grind/*                 vendored, deliberately NOT imported

An aggregator is placed next to its directory as `<Dir>.lean`; if that path is
already taken by a test file (`Test/Sat.lean`, `Test/FinSearch.lean`) it goes
inside the directory as `Suite.lean`, since the module name is already used.
A parent aggregator imports its nested subdirectory's aggregator rather than
listing the same modules twice.
"""
import os

ROOT = "/root/lynth"
TEST = os.path.join(ROOT, "Test")

HEADER = """-- `{path}` -- {kind}
--
{blurb}--
-- Generated by `Scripts/gen_test_aggregators.py`; do not edit by hand.
-- Every module listed below is a test that currently passes.
"""


def comment(text):
    """Prefix every line with `-- ` so a multi-line blurb stays a comment."""
    text = text.rstrip("\n")
    return "\n".join(("-- " + l).rstrip() for l in text.split("\n")) + "\n"


MARKER = "Generated by `Scripts/gen_test_aggregators.py`"


def is_generated(path):
    """True for a file this script wrote, so re-runs overwrite instead of
    treating their output as a test and emitting a second aggregator."""
    try:
        with open(path, encoding="utf-8") as f:
            return MARKER in f.read(4096)
    except OSError:
        return False


def module_of(path):
    """`Test/FinDomain/Meta/A.lean` -> `Test.FinDomain.Meta.A`"""
    return os.path.relpath(path, ROOT)[:-len(".lean")].replace(os.sep, ".")


def module_of_dir(path):
    """`Test/FinDomain/Meta` -> `Test.FinDomain.Meta` (a directory, so there
    is no `.lean` suffix to strip)."""
    return os.path.relpath(path, ROOT).replace(os.sep, ".")


def sync_lakefile(root_modules, top_dirs):
    """Rewrite the `globs` list of the `Test` lean_lib in lakefile.toml.

    Generated rather than hand-written because Lake's `*` is multi-component:
    `Test.*` happily matches `Test.Grind.Fast.grind_beta`, so the vendored suite
    cannot be excluded by a wildcard.  Instead every module at one level is named
    explicitly and each top-level subdirectory uses `+` ("this and everything
    below"), which is checked against the layout this script just produced.
    """
    import re
    path = os.path.join(ROOT, "lakefile.toml")
    src = open(path, encoding="utf-8").read()
    globs = ["Test"] + sorted(root_modules)
    for d in sorted(top_dirs):
        m = module_of_dir(d)
        globs += [m, m + ".+"]
    globs = list(dict.fromkeys(globs))      # a directory that is also a
                                            # root-level test name appears twice
    body = "globs = [\n" + "".join('  "%s",\n' % g for g in globs) + "]"
    new = re.sub(r'(name = "Test"\n)globs = \[.*?\]',
                 lambda _m: 'name = "Test"\n' + body, src, flags=re.S)
    if new == src:
        print("  WARNING: could not find the Test globs block in lakefile.toml")
    else:
        open(path, "w", encoding="utf-8").write(new)
    return globs


def main():
    files = []
    for root, dirs, names in os.walk(TEST):
        dirs[:] = [d for d in dirs if d != "Grind"]
        for n in sorted(names):
            p = os.path.join(root, n)
            if n.endswith(".lean") and not is_generated(p):
                files.append(p)
    files.sort()
    existing = set(files)

    # deepest directories first, so a child aggregator exists before the parent
    # needs to reference it
    dirs = sorted({os.path.dirname(p) for p in files
                   if os.path.dirname(p) != TEST},
                  key=lambda d: (-d.count(os.sep), d))

    agg_of = {}                       # directory -> aggregator path
    for d in dirs:
        direct = [p for p in files if os.path.dirname(p) == d]
        subs = sorted(x for x in dirs
                      if os.path.dirname(x) == d)
        target = os.path.join(os.path.dirname(d),
                              os.path.basename(d) + ".lean")
        if target in existing or target in agg_of.values():
            target = os.path.join(d, "Suite.lean")
        body = [HEADER.format(
            path=os.path.relpath(target, ROOT), kind="subdirectory aggregator",
            blurb=comment("Imports %d test module%s from `%s/`.\n"
                          % (len(direct), "" if len(direct) == 1 else "s",
                             os.path.relpath(d, ROOT))))]
        body += ["import %s" % module_of(p) for p in direct]
        if subs:
            body.append("")
            body.append("-- nested subdirectories")
            body += ["import %s" % module_of(agg_of[s]) for s in subs]
        os.makedirs(os.path.dirname(target), exist_ok=True)
        open(target, "w").write("\n".join(body) + "\n")
        agg_of[d] = target

    top = sorted(d for d in dirs if os.path.dirname(d) == TEST)
    agg_paths = set(agg_of.values())
    root_tests = sorted(p for p in files
                        if os.path.dirname(p) == TEST and p not in agg_paths)

    out = [HEADER.format(
        path="Test.lean", kind="root aggregator",
        blurb=comment(
            "Imports every currently-passing test in `Test/`.  Each\n"
            "subdirectory is funnelled through its own aggregator, so this\n"
            "file stays readable and a subtree can be built on its own.\n"
            "The vendored `Test/Grind/` suite is deliberately absent.\n"))]
    out.append("-- subdirectory aggregators")
    out += ["import %s" % module_of(agg_of[d]) for d in top]
    out += ["", "-- root-level tests"]
    out += ["import %s" % module_of(p) for p in root_tests]
    open(os.path.join(ROOT, "Test.lean"), "w").write("\n".join(out) + "\n")

    globs = sync_lakefile([module_of(p) for p in root_tests], top)

    print("aggregators:")
    for d in top + [x for x in dirs if os.path.dirname(x) != TEST]:
        t = agg_of[d]
        print("  %-32s -> %s" % (os.path.relpath(t, ROOT),
                                 os.path.basename(t)))
    print("Test.lean: %d aggregators + %d root tests = %d imports"
          % (len(top), len(root_tests), len(top) + len(root_tests)))
    print("lakefile globs (%d):" % len(globs))
    print("  " + ", ".join(globs))


if __name__ == "__main__":
    main()
