/-
Copyright (c) 2024 Amazon.com, Inc. or its affiliates. All Rights Reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Leonardo de Moura
-/
module
prelude
public import Lean.Meta.Tactic.Revert
import Init.Data.Range.Polymorphic.Iterators
open Lean.Meta
public section
namespace Lean.Lynth.Grind

/-- Mark used by `markAccessible` -/
private def grindMark := "__grind_mark"

/--
Return `some originalName` if `name` is a name generated by `markAccessible`.
`originalName` is the original name before `markAccessible` was invoked.
-/
def getOriginalName? (name : Name) : Option Name := do
  match name with
  | .str p s => if s == grindMark then some p else none
  | _ => none

def markGrindName (userName : Name) : Name :=
  Name.str userName grindMark

end Lean.Lynth.Grind
